version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
    ports:
      - '6543:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
