version: '3.8'
services:
  postgres:
    image: postgres:15
    env_file:
      - ./ClimbingTrainerAPI/.env
    ports:
      - '6543:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./ClimbingTrainerAPI:/ClimbingTrainerAPI
    env_file:
      - ./ClimbingTrainerAPI/.env
    depends_on:
      - postgres
    links:
      - postgres
